apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f836kq6o9-python
  janus-idp.io/tekton: f836kq6o9-python
  backstage.io/kubernetes-id: f836kq6o9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f836kq6o9-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
